fix

diff --git a/.github/workflows/cluster-initialization.yml b/.github/workflows/cluster-initialization.yml
--- a/.github/workflows/cluster-initialization.yml
+++ b/.github/workflows/cluster-initialization.yml
@@ -73,16 +73,21 @@ jobs:
         run:
           pip install requests
 
-      - name: deploy cluster
-        env:
-          GITHUB_USERNAME: gaoran10
-          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
-          ISSUE_NUMBER: ${{ github.event.issue.number }}
-          RUN_ID: ${{ github.run_id }}
-          COMMENT_BODY: ${{ github.event.issue.body }}
-          TEST_ACTION: create
-        run: |
-          cd ./hello/chaos-mesh-template
+#      - name: deploy cluster
+#        env:
+#          GITHUB_USERNAME: gaoran10
+#          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
+#          ISSUE_NUMBER: ${{ github.event.issue.number }}
+#          RUN_ID: ${{ github.run_id }}
+#          COMMENT_BODY: ${{ github.event.issue.body }}
+#          TEST_ACTION: create
+#        run: |
+#          cd charts
+#          python ../hello/scripts/chaos-cluster-manager.py
+#          ./scripts/pulsar/prepare_helm_release.sh -n 'chaos-${{ github.event.issue.number }}' -k 'chaos-pulsar-${{ github.event.issue.number }}' -c
+#          helm repo add loki https://grafana.github.io/loki/charts
+#          helm dependency update charts/pulsar-custom
+#          helm install --set initialize=true --set namespace='chaos-${{ github.event.issue.number }}' --values ./charts/pulsar-custom/values.yaml 'chaos-pulsar-${{ github.event.issue.number }}'  ./charts/pulsar-custom/ --debug --wait --timeout 30m
 
       - name: checkout chaos-test repo
         uses: actions/checkout@v2
@@ -97,10 +102,8 @@ jobs:
           cd ./chaos-test
           nohup kubectl port-forward -n 'chaos-${{ github.event.issue.number }}' svc/chaos-pulsar-${{ github.event.issue.number }}-proxy 6650:6650 8080:8080 > port-forward.out 2>&1 &
           mvn -Dtest=SimpleMessagingTest clean test
-          echo 'check port forward log'
-          cat port-forward.out
 
-      - name: deploy cluster finish
+      - name: check port forward log
         env:
           GITHUB_USERNAME: gaoran10
           GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
@@ -109,4 +112,17 @@ jobs:
           TEST_ACTION: finish
         if: ${{ always() ||  success() || cancelled() || failure() }}
         run: |
-          python ./hello/scripts/chaos-cluster-manager.py
+          ps -ef | grep port-forward
+          cd ./chaos-test
+          cat port-forward.out
+
+#      - name: deploy cluster finish
+#        env:
+#          GITHUB_USERNAME: gaoran10
+#          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
+#          ISSUE_NUMBER: ${{ github.event.issue.number }}
+#          STATUS: ${{ job.status }}
+#          TEST_ACTION: finish
+#        if: ${{ always() ||  success() || cancelled() || failure() }}
+#        run: |
+#          python ./hello/scripts/chaos-cluster-manager.py
